### ISSUE TITLE
Suport for YML

### ISSUE THREAD

**Issue by Tushar-Tilwani** [shalupov/idea-cloudformation#77] opened 2017-02-06 23:17 UTC
Will the plugin support yaml templates as well in the future?

**Comment by snrklyc** [comment] 2017-02-08 19:05
There's an active yaml branch which is 55 commits ahead of master, guess the answer is yes.

**Comment by shalupov** [comment] 2017-02-25 10:21
yes, it's a duplicate of #55

**Closed by shalupov** 2017-02-25 10:21 UTC
